let client=null, products=[], contents=[];
const settings=JSON.parse(localStorage.getItem('nova_supabase')||'null');
if(settings){urlInput.value=settings.url;keyInput.value=settings.key;initClient(settings.url,settings.key,true)}
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>showPage(b.dataset.page));
function showPage(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.page===id));title.textContent={dashboard:'Dashboard',products:'Product Center',content:'Content Queue',settings:'Connection'}[id]}
function msg(text,type){setupMessage.textContent=text;setupMessage.className='message show '+type}
async function initClient(url,key,silent=false){try{client=supabase.createClient(url,key);const {error}=await client.from('products').select('id').limit(1);if(error)throw error;localStorage.setItem('nova_supabase',JSON.stringify({url,key}));connectionBadge.textContent='เชื่อมต่อ Supabase แล้ว';connectionBadge.className='connection online';if(!silent)msg('เชื่อมต่อสำเร็จ ฐานข้อมูลพร้อมใช้งาน','ok');await loadAll()}catch(e){client=null;connectionBadge.textContent='เชื่อมต่อไม่สำเร็จ';connectionBadge.className='connection offline';if(!silent)msg(e.message,'error')}}
connectBtn.onclick=()=>initClient(urlInput.value.trim(),keyInput.value.trim());
refreshBtn.onclick=()=>loadAll();
async function loadAll(){if(!client)return;const [p,c]=await Promise.all([client.from('products').select('*').order('created_at',{ascending:false}),client.from('contents').select('*').order('created_at',{ascending:false})]);if(p.error||c.error){alert((p.error||c.error).message);return}products=p.data||[];contents=c.data||[];render()}
function money(n){return '฿'+Number(n||0).toLocaleString('th-TH')}
function render(){revenueKpi.textContent=money(products.reduce((s,p)=>s+Number(p.revenue||0),0));productKpi.textContent=products.length;contentKpi.textContent=contents.length;postedKpi.textContent=contents.filter(c=>c.status==='Posted').length;
pipeline.innerHTML=contents.slice(0,7).map(c=>`<div class="item"><span>${c.title}<small>${c.character} · ${c.platform}</small></span><span class="badge">${c.status}</span></div>`).join('')||'<p>ยังไม่มีข้อมูล</p>';
topProducts.innerHTML=[...products].sort((a,b)=>b.revenue-a.revenue).slice(0,7).map(p=>`<div class="item"><span>${p.name}<small>${p.category}</small></span><b>${money(p.revenue)}</b></div>`).join('')||'<p>ยังไม่มีข้อมูล</p>';
productRows.innerHTML=products.map(p=>`<tr><td>${p.name}</td><td>${p.category}</td><td>${money(p.price)}</td><td>${money(p.commission)}</td><td>${money(p.revenue)}</td><td>${p.status}</td><td><button class="danger" onclick="delProduct('${p.id}')">ลบ</button></td></tr>`).join('');
const sts=['Idea','Script','Production','Ready','Posted'];kanban.innerHTML=sts.map(s=>`<div class="column"><h3>${s} (${contents.filter(c=>c.status===s).length})</h3>${contents.filter(c=>c.status===s).map(c=>`<div class="card"><b>${c.title}</b><small>${c.character} · ${c.platform}</small><select onchange="moveContent('${c.id}',this.value)">${sts.map(x=>`<option ${x===c.status?'selected':''}>${x}</option>`).join('')}</select></div>`).join('')}</div>`).join('')}
openProduct.onclick=()=>productDialog.showModal();openContent.onclick=()=>contentDialog.showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.close).close());
productForm.onsubmit=async e=>{e.preventDefault();if(!client)return alert('กรุณาเชื่อม Supabase ก่อน');const payload={name:pName.value,brand:pBrand.value,category:pCategory.value,price:+pPrice.value,commission:+pCommission.value,affiliate_link:pLink.value,status:pStatus.value,revenue:0};const {error}=await client.from('products').insert(payload);if(error)return alert(error.message);productDialog.close();productForm.reset();await loadAll()};
contentForm.onsubmit=async e=>{e.preventDefault();if(!client)return alert('กรุณาเชื่อม Supabase ก่อน');const payload={title:cTitle.value,character:cCharacter.value,platform:cPlatform.value,status:cStatus.value,hook:cHook.value};const {error}=await client.from('contents').insert(payload);if(error)return alert(error.message);contentDialog.close();contentForm.reset();await loadAll()};
window.delProduct=async id=>{if(confirm('ลบสินค้านี้หรือไม่?')){const {error}=await client.from('products').delete().eq('id',id);if(error)alert(error.message);else loadAll()}};
window.moveContent=async(id,status)=>{const {error}=await client.from('contents').update({status}).eq('id',id);if(error)alert(error.message);else loadAll()};
